cameras:

  - name: cam_front # name of camera
    camera_type: usb_camera # name of pkg # Currently supports 'usb_camera' and 'realsense2_camera'
    param_path: so101_usb_cam.yaml # path to camera specific config file
    namespace: follower # ns (info of cam location)

  - name: cam_side
    camera_type: realsense2_camera
    param_path: so101_realsense2.yaml
    namespace: static_camera
