sdr:
  ros__parameters:
    # The base name for each bag file. A timestamp will be appended to this.
    bag_name_prefix: "robot_data"

    # The parent directory where all recording session folders will be saved.
    copy_destination: "<your abs path to the desired dir>"

    # Maximum size of each individual .db3 file in bytes before splitting.
    max_file_size: 1073741824  # 1024 MiB * 1024 * 1024

    # List of topics and their types to record.
    topic_names: [
      "/follower/joint_states",
      "/leader/joint_states",
      "/follower/cam_front/image_raw",
      "/static_camera/cam_side/color/image_raw"

    ]
    topic_types: [
      "sensor_msgs/msg/JointState",
      "sensor_msgs/msg/JointState",
      "sensor_msgs/msg/Image",
      "sensor_msgs/msg/Image"
    ]

    # The task description which will be used for language model prompts for the robot's agent.
    task: ""
