# Default initial positions for so101_new_calib's ros2_control fake system
initial_positions:
  shoulder_pan: 0.0
  shoulder_lift: -1.75
  elbow_flex: 1.58
  wrist_flex: 1.0
  wrist_roll: 0.25
  gripper: 0.0
