profile:
  name: vr_server_only
  description: "VR server only (Unity TCP Endpoint)"
  actions:
    - type: node
      package: ros_tcp_endpoint
      executable: default_server_endpoint
      name: ros_tcp_endpoint
      parameters:
        ROS_IP: ${ros_ip}
        ROS_TCP_PORT: ${ros_tcp_port}
